server:
  port: 2772

spring:
  application:
    name: Course Management
  datasource:
    url: jdbc:postgresql:course
    username: postgres
    password: Hoaibao211
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  redis:
    host: localhost
    port: 6379

logging:
  level:
    org:
      hibernate: WARN
      springframework: WARN