server:
  port: 2772

spring:
  datasource:
    #url: jdbc:postgresql:course
    url: jdbc:postgresql://172.17.0.2:5432/course
    username: postgres
    password: 123456
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    org:
      hibernate: WARN
      springframework: WARN